### ISSUE TITLE
change the operator log level to info

### ISSUE THREAD

**Issue by lance5890** [openshift/cluster-openshift-controller-manager-operator#290]
1. The cluster-openshift-controller-manager-operator log level now is set to 4, which will generate more use useless logs, as follows:
<img width="437" alt="image" src="https://github.com/openshift/cluster-openshift-controller-manager-operator/assets/30207518/53d4ebfc-9b6c-4ad1-b824-622af0bc16dc">

2. This log level is set by the deployment as follows:
https://github.com/openshift/cluster-openshift-controller-manager-operator/blob/9b7ea79904af754d3bb792d6d3284f83564b25e7/manifests/09_deployment.yaml#L46
<img width="622" alt="image" src="https://github.com/openshift/cluster-openshift-controller-manager-operator/assets/30207518/06ffda31-3fdd-4d3b-a31f-d32c0bdda0f3">

3. But in the cluster-openshift-apiserver-operator, the log level is default , not set to 4
<img width="558" alt="image" src="https://github.com/openshift/cluster-openshift-controller-manager-operator/assets/30207518/43359ece-018a-4571-8d74-c5bbc7b71b74">

**Comment by lance5890** [comment]
@atiratree

**Comment by atiratree** [comment]
OCM-o seems to have a bigger deficit in this area: https://github.com/openshift/cluster-openshift-controller-manager-operator/pull/289#discussion_r1194201772

**Comment by atiratree** [comment]
this was already fixed in https://github.com/openshift/cluster-openshift-controller-manager-operator/pull/292 and https://github.com/openshift/cluster-openshift-controller-manager-operator/pull/289

/close
